server:
  port: 8000
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;INIT=CREATE SCHEMA IF NOT EXISTS test
    username: sa
    password:

  session:
    timeout: 3600  # 세션 타임아웃 (초 단위)
  security:
    max-sessions: 1  # 동시 세션 제어
    max-sessions-prevents-login: true  # 최대 세션 수 초과 시 로그인 방지

  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
      data-locations: [ classpath:schema.sql,
                        classpath:dummy/data.sql ]

  jpa:
    defer-datasource:
      initialization: true
      database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false


#------------------------------------------------------------
jwt:
  secret-key: U21hcnRTY29yZV9DbHViTWFuYWdlcl9Qcm9qZWN0X1NlY3JldF9LZXlfU21hcnRTY29yZV9DbHViTWFuYWdlcl9Qcm9qZWN0X1NlY3JldF9LZXk=
  access-ttl: 3600 #?(60)*?(60) = 1??

reg-no:
  key: MTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXY=